import numpy as np
import matplotlib.pyplot as plt

def simulate_latency_gravity():
    """
    Toy Model: Simulates a test particle moving in a latency potential 
    generated by a central processing load (Mass).
    """
    # Constants
    G = 1.0 # Computational Resistance
    M = 100.0 # Central Processing Load (Mass)
    dt = 0.01
    steps = 1000
    
    # Initial state of test particle
    pos = np.array([10.0, 0.0])
    vel = np.array([0.0, 3.0])
    
    trajectory = []
    
    for _ in range(steps):
        r = np.linalg.norm(pos)
        # Latency Potential phi = -G*M/r
        # Acceleration a = -grad phi = -G*M/r^2 * (pos/r)
        accel = -G * M / r**3 * pos
        
        vel += accel * dt
        pos += vel * dt
        
        trajectory.append(pos.copy())
    
    trajectory = np.array(trajectory)
    
    plt.figure(figsize=(8, 8))
    plt.plot(trajectory[:, 0], trajectory[:, 1], label='Test Particle Trajectory')
    plt.scatter([0], [0], color='red', label='Central Processing Load (M)')
    plt.title('L-ToEC Toy Model: Motion in Latency Potential')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.legend()
    plt.grid(True)
    plt.axis('equal')
    plt.savefig('docs/physics/rigor_upgrade/latency_sim.png')
    print("Simulation complete. Plot saved to docs/physics/rigor_upgrade/latency_sim.png")

if __name__ == "__main__":
    simulate_latency_gravity()
