"""
Memory record schema and data models.

Defines the MemoryRecord structure for storing and retrieving memories.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any, Literal
from enum import Enum
from pydantic import BaseModel, Field, field_validator


class MemoryRecord(BaseModel):
    """
    Memory record schema for storing facts, insights, and information.
    
    Attributes:
        id: Unique identifier (auto-generated by storage)
        namespace: Hierarchical namespace (e.g., "math.sage.api")
        tags: List of tags for categorization
        text: The actual memory content/fact
        importance: Importance score from 0.0 to 1.0
        created_at: Timestamp when memory was created
        last_used_at: Timestamp when memory was last retrieved
        embedding: Optional embedding vector (stored separately in FAISS)
        valid_from: Optional timestamp when this fact became true
        valid_until: Optional timestamp when this fact stopped being true
        temporal_scope: Optional temporal classification ("past", "present", "future", "timeless")
    """
    
    id: Optional[int] = None
    namespace: str = Field(..., min_length=1, description="Hierarchical namespace for the memory")
    tags: List[str] = Field(default_factory=list, description="Tags for categorization")
    text: str = Field(..., min_length=1, description="The memory content/fact")
    importance: float = Field(..., ge=0.0, le=1.0, description="Importance score from 0.0 to 1.0")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_used_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    embedding: Optional[List[float]] = Field(default=None, description="Embedding vector (stored in FAISS)")
    valid_from: Optional[datetime] = Field(default=None, description="Timestamp when this fact became true")
    valid_until: Optional[datetime] = Field(default=None, description="Timestamp when this fact stopped being true")
    temporal_scope: Optional[Literal["past", "present", "future", "timeless"]] = Field(
        default=None, description="Temporal classification"
    )
    
    @field_validator('namespace')
    @classmethod
    def validate_namespace(cls, v: str) -> str:
        """Validate namespace is not empty."""
        if not v or not v.strip():
            raise ValueError("Namespace cannot be empty")
        return v.strip()
    
    @field_validator('text')
    @classmethod
    def validate_text(cls, v: str) -> str:
        """Validate text is not empty."""
        if not v or not v.strip():
            raise ValueError("Text cannot be empty")
        return v.strip()
    
    @field_validator('tags')
    @classmethod
    def validate_tags(cls, v: List[str]) -> List[str]:
        """Validate and clean tags."""
        # Remove empty tags and strip whitespace
        cleaned = [tag.strip() for tag in v if tag and tag.strip()]
        return cleaned
    
    @field_validator('importance')
    @classmethod
    def validate_importance(cls, v: float) -> float:
        """Validate importance is in range [0.0, 1.0]."""
        if not 0.0 <= v <= 1.0:
            raise ValueError(f"Importance must be between 0.0 and 1.0, got {v}")
        return v
    
    def update_last_used(self) -> None:
        """Update the last_used_at timestamp to now."""
        self.last_used_at = datetime.now(timezone.utc)


class RelationType(str, Enum):
    """
    Types of relationships between memories.
    
    Logical relationships:
    - SUPPORTS: Evidence for another memory
    - CONTRADICTS: Conflicts with another memory
    - SUPERSEDES: Replaces/updates another memory
    
    Structural relationships:
    - ELABORATES: Adds detail to another memory
    - SUMMARIZES: Condenses another memory
    - REFERENCES: General reference/citation
    
    Causal relationships:
    - CAUSES: Leads to another memory/event
    - CAUSED_BY: Resulted from another memory/event
    
    Temporal relationships:
    - PRECEDES: Happened before
    - FOLLOWS: Happened after
    
    Semantic relationships:
    - SIMILAR_TO: Semantically similar (auto-detected)
    - RELATED_TO: General relation
    """
    # Logical relationships
    SUPPORTS = "supports"
    CONTRADICTS = "contradicts"
    SUPERSEDES = "supersedes"
    
    # Structural relationships
    ELABORATES = "elaborates"
    SUMMARIZES = "summarizes"
    REFERENCES = "references"
    
    # Causal relationships
    CAUSES = "causes"
    CAUSED_BY = "caused_by"
    
    # Temporal relationships
    PRECEDES = "precedes"
    FOLLOWS = "follows"
    
    # Semantic relationships
    SIMILAR_TO = "similar_to"
    RELATED_TO = "related_to"


class RelationshipRecord(BaseModel):
    """
    Represents a relationship between two memories.
    
    Attributes:
        source_id: ID of the source memory
        target_id: ID of the target memory
        relation_type: Type of relationship
        strength: Relationship strength from 0.0 to 1.0
        bidirectional: Whether relationship goes both ways
        metadata: Optional additional context (JSON-serializable dict)
        id: Unique identifier (auto-generated by storage)
        created_at: Timestamp when relationship was created
    """
    
    source_id: int = Field(..., description="ID of the source memory")
    target_id: int = Field(..., description="ID of the target memory")
    relation_type: RelationType = Field(..., description="Type of relationship")
    strength: float = Field(default=1.0, ge=0.0, le=1.0, description="Relationship strength from 0.0 to 1.0")
    bidirectional: bool = Field(default=False, description="Whether relationship goes both ways")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Additional context")
    id: Optional[int] = Field(default=None, description="Unique identifier (auto-generated)")
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when relationship was created")
    
    @field_validator('strength')
    @classmethod
    def validate_strength(cls, v: float) -> float:
        """Validate strength is in range [0.0, 1.0]."""
        if not 0.0 <= v <= 1.0:
            raise ValueError(f"Strength must be between 0.0 and 1.0, got {v}")
        return v

