"""
Tests for unified token system: token_auth JWT tokens with DEA approval system.

Tests that JWT tokens from token_auth work with the approval system.
"""

from __future__ import annotations

import pytest
import os
import time
import tempfile
from pathlib import Path

from broca.environment.actuators.approval import ApprovalSystem, VerificationResult
from broca.environment.tools.environment_tool import EnvironmentAccessTool
from broca.token_auth.token import generate_token, verify_token
from broca.token_auth.defaults import get_default_identity


class TestJWTTokenInApprovalSystem:
    """Test that JWT tokens from token_auth work with approval system."""
    
    def test_jwt_token_accepted_by_verify_approval(self, monkeypatch):
        """Test that JWT tokens generated by token_auth are accepted by verify_approval."""
        monkeypatch.setenv("BROCA_TOKEN_SECRET", "test_secret_key_123")
        
        # Generate JWT token using token_auth
        identity = get_default_identity()
        token, payload = generate_token(
            sub=identity.get("sub", "test.user"),
            name=identity.get("name", "Test User"),
            scopes=["filesystem:write", "project:write", "memory:write"],
            expiry_seconds=300,
            secret_key="test_secret_key_123"
        )
        
        # Create approval system and verify the JWT token
        approval_system = ApprovalSystem()
        result = approval_system.verify_approval(token)
        
        assert result.valid is True
        assert result.error is None
    
    def test_jwt_token_with_insufficient_scopes_rejected(self, monkeypatch):
        """Test that JWT tokens without required scopes are rejected."""
        monkeypatch.setenv("BROCA_TOKEN_SECRET", "test_secret_key_123")
        
        # Generate JWT token without filesystem:write scope
        identity = get_default_identity()
        token, payload = generate_token(
            sub=identity.get("sub", "test.user"),
            name=identity.get("name", "Test User"),
            scopes=["project:write"],  # Missing filesystem:write
            expiry_seconds=300,
            secret_key="test_secret_key_123"
        )
        
        # Create approval system and verify the JWT token with required scopes
        approval_system = ApprovalSystem()
        result = approval_system.verify_approval(
            token,
            required_scopes=["filesystem:write"]  # Require filesystem:write scope
        )
        
        # Should be rejected due to insufficient scopes
        assert result.valid is False
        assert "scope" in result.error.lower() or "permission" in result.error.lower()
    
    def test_expired_jwt_token_rejected(self, monkeypatch):
        """Test that expired JWT tokens are rejected."""
        monkeypatch.setenv("BROCA_TOKEN_SECRET", "test_secret_key_123")
        
        # Generate JWT token with very short expiration
        identity = get_default_identity()
        token, payload = generate_token(
            sub=identity.get("sub", "test.user"),
            name=identity.get("name", "Test User"),
            scopes=["filesystem:write"],
            expiry_seconds=1,  # 1 second expiration
            secret_key="test_secret_key_123"
        )
        
        # Wait for expiration
        time.sleep(1.5)
        
        # Create approval system and verify the expired JWT token
        approval_system = ApprovalSystem()
        result = approval_system.verify_approval(token)
        
        assert result.valid is False
        assert "expired" in result.error.lower()
    
    def test_invalid_jwt_token_rejected(self, monkeypatch):
        """Test that invalid JWT tokens are rejected."""
        monkeypatch.setenv("BROCA_TOKEN_SECRET", "test_secret_key_123")
        
        approval_system = ApprovalSystem()
        
        # Test with malformed token
        result = approval_system.verify_approval("not.a.valid.jwt.token")
        assert result.valid is False
        
        # Test with tampered token
        identity = get_default_identity()
        token, payload = generate_token(
            sub=identity.get("sub", "test.user"),
            name=identity.get("name", "Test User"),
            scopes=["filesystem:write"],
            expiry_seconds=300,
            secret_key="test_secret_key_123"
        )
        tampered_token = token[:-1] + "X"
        result = approval_system.verify_approval(tampered_token)
        assert result.valid is False
    
    def test_jwt_token_used_in_control_actuator(self, monkeypatch):
        """Test that JWT tokens can be used in control_actuator operations."""
        monkeypatch.setenv("BROCA_TOKEN_SECRET", "test_secret_key_123")
        
        tool = EnvironmentAccessTool()
        
        # Escalate to AUTONOMOUS
        result = tool.execute(
            action="request_escalation",
            target_level="AUTONOMOUS",
            rationale="Test"
        )
        request_id = result["request_id"]
        tool.execute(action="approve_escalation", request_id=request_id)
        
        # Generate JWT token using token_auth
        identity = get_default_identity()
        jwt_token, payload = generate_token(
            sub=identity.get("sub", "test.user"),
            name=identity.get("name", "Test User"),
            scopes=["filesystem:write", "project:write", "memory:write"],
            expiry_seconds=300,
            secret_key="test_secret_key_123"
        )
        
        # Use JWT token in control_actuator
        with tempfile.TemporaryDirectory() as tmpdir:
            test_file = Path(tmpdir) / "test.txt"
            result = tool.execute(
                action="control_actuator",
                actuator_id="filesystem_actuator",
                operation="create_file",
                parameters={
                    "path": str(test_file),
                    "content": "test content",
                    "approval_token": jwt_token
                }
            )
            
            assert result["success"] is True
            assert test_file.exists()
            assert test_file.read_text() == "test content"


class TestApprovalSystemGeneratesJWT:
    """Test that approval system generates JWT tokens."""
    
    def test_generate_token_creates_jwt(self, monkeypatch):
        """Test that generate_token creates JWT tokens instead of UUID tokens."""
        monkeypatch.setenv("BROCA_TOKEN_SECRET", "test_secret_key_123")
        
        approval_system = ApprovalSystem()
        
        # Create and approve a request
        request = approval_system.request_approval(
            operation="create_file",
            parameters={"path": "/tmp/test.txt", "content": "test"},
            rationale="Test"
        )
        request.approved = True
        
        # Generate token
        token = approval_system.generate_token(request.request_id)
        
        # Token should be a JWT (has dots separating parts)
        assert "." in token
        parts = token.split(".")
        assert len(parts) == 3  # JWT has 3 parts: header.payload.signature
        
        # Token should be verifiable using token_auth
        payload = verify_token(token, "test_secret_key_123")
        assert payload is not None
        assert "sub" in payload
        assert "scopes" in payload
        assert "request_id" in payload  # Should include request_id for traceability
    
    def test_generated_jwt_token_has_request_id(self, monkeypatch):
        """Test that generated JWT tokens include request_id in payload."""
        monkeypatch.setenv("BROCA_TOKEN_SECRET", "test_secret_key_123")
        
        approval_system = ApprovalSystem()
        
        # Create and approve a request
        request = approval_system.request_approval(
            operation="create_file",
            parameters={"path": "/tmp/test.txt", "content": "test"},
            rationale="Test"
        )
        request.approved = True
        
        # Generate token
        token = approval_system.generate_token(request.request_id)
        
        # Verify token and check payload
        payload = verify_token(token, "test_secret_key_123")
        assert payload["request_id"] == request.request_id
    
    def test_generated_jwt_token_has_appropriate_scopes(self, monkeypatch):
        """Test that generated JWT tokens have appropriate scopes."""
        monkeypatch.setenv("BROCA_TOKEN_SECRET", "test_secret_key_123")
        
        approval_system = ApprovalSystem()
        
        # Create and approve a request for filesystem operation
        request = approval_system.request_approval(
            operation="create_file",
            parameters={"path": "/tmp/test.txt", "content": "test"},
            rationale="Test"
        )
        request.approved = True
        
        # Generate token
        token = approval_system.generate_token(request.request_id)
        
        # Verify token and check scopes
        payload = verify_token(token, "test_secret_key_123")
        assert "scopes" in payload
        assert isinstance(payload["scopes"], list)
        # Should include filesystem:write for filesystem operations
        assert "filesystem:write" in payload["scopes"]


class TestApprovalWorkflowWithJWT:
    """Test complete approval workflow with JWT tokens."""
    
    def test_full_workflow_with_jwt_tokens(self, monkeypatch):
        """Test complete workflow: request → approve → generate JWT token → use."""
        monkeypatch.setenv("BROCA_TOKEN_SECRET", "test_secret_key_123")
        
        tool = EnvironmentAccessTool()
        
        # Escalate to AUTONOMOUS
        result = tool.execute(
            action="request_escalation",
            target_level="AUTONOMOUS",
            rationale="Test"
        )
        request_id = result["request_id"]
        tool.execute(action="approve_escalation", request_id=request_id)
        
        with tempfile.TemporaryDirectory() as tmpdir:
            test_file = Path(tmpdir) / "test.txt"
            
            # Request approval
            result = tool.execute(
                action="request_actuator_approval",
                actuator_id="filesystem_actuator",
                operation="create_file",
                parameters={"path": str(test_file), "content": "test"},
                rationale="Test file creation"
            )
            assert result["success"] is True
            approval_request_id = result["approval_request_id"]
            
            # Approve request (should generate JWT token)
            result = tool.execute(
                action="approve_actuator_request",
                approval_request_id=approval_request_id
            )
            assert result["success"] is True
            token = result.get("approval_token")
            assert token is not None
            
            # Token should be JWT format
            assert "." in token
            parts = token.split(".")
            assert len(parts) == 3
            
            # Use token
            result = tool.execute(
                action="control_actuator",
                actuator_id="filesystem_actuator",
                operation="create_file",
                parameters={
                    "path": str(test_file),
                    "content": "test content",
                    "approval_token": token
                }
            )
            assert result["success"] is True
            assert test_file.exists()
    
    def test_cli_generated_token_works_with_dea(self, monkeypatch):
        """Test that tokens generated via CLI (broca-token generate) work with DEA."""
        monkeypatch.setenv("BROCA_TOKEN_SECRET", "test_secret_key_123")
        
        tool = EnvironmentAccessTool()
        
        # Escalate to AUTONOMOUS
        result = tool.execute(
            action="request_escalation",
            target_level="AUTONOMOUS",
            rationale="Test"
        )
        request_id = result["request_id"]
        tool.execute(action="approve_escalation", request_id=request_id)
        
        # Generate token using token_auth (simulating CLI generation)
        identity = get_default_identity()
        cli_token, payload = generate_token(
            sub=identity.get("sub", "test.user"),
            name=identity.get("name", "Test User"),
            scopes=["filesystem:write", "project:write", "memory:write"],
            expiry_seconds=300,
            secret_key="test_secret_key_123"
        )
        
        # Use CLI-generated token in control_actuator
        with tempfile.TemporaryDirectory() as tmpdir:
            test_file = Path(tmpdir) / "test.txt"
            result = tool.execute(
                action="control_actuator",
                actuator_id="filesystem_actuator",
                operation="create_file",
                parameters={
                    "path": str(test_file),
                    "content": "test content",
                    "approval_token": cli_token
                }
            )
            
            assert result["success"] is True
            assert test_file.exists()


class TestBackwardCompatibility:
    """Test backward compatibility during transition."""
    
    def test_uuid_tokens_still_work_during_transition(self, monkeypatch):
        """Test that UUID tokens (if any exist) still work during transition period."""
        monkeypatch.setenv("BROCA_TOKEN_SECRET", "test_secret_key_123")
        
        approval_system = ApprovalSystem()
        
        # Create and approve a request
        request = approval_system.request_approval(
            operation="create_file",
            parameters={"path": "/tmp/test.txt", "content": "test"},
            rationale="Test"
        )
        request.approved = True
        
        # Manually create a UUID token (simulating old format)
        import uuid
        from datetime import datetime, timezone, timedelta
        from broca.environment.actuators.approval import ApprovalToken
        
        old_token = str(uuid.uuid4())
        expires_at = datetime.now(timezone.utc) + timedelta(seconds=300)
        approval_token = ApprovalToken(
            token=old_token,
            request_id=request.request_id,
            expires_at=expires_at
        )
        approval_system.tokens[old_token] = approval_token
        
        # UUID token should still be verifiable
        result = approval_system.verify_approval(old_token)
        assert result.valid is True


class TestTokenSecretFromEnvFile:
    """Test that tokens work when secret is only in .env file (not in environment)."""
    
    def test_token_generation_with_secret_in_env_file(self, monkeypatch):
        """Test that token generation works when secret is only in .env file."""
        # Remove from environment if present
        monkeypatch.delenv("BROCA_TOKEN_SECRET", raising=False)
        
        # Create temporary directory with .env file
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"
            test_secret = "test_secret_from_env_file_12345"
            env_file.write_text(f"BROCA_TOKEN_SECRET={test_secret}\n")
            
            # Change to the temporary directory so .env is found
            original_cwd = os.getcwd()
            try:
                os.chdir(tmpdir)
                
                # Force reload of dotenv by calling load_dotenv with explicit path
                from dotenv import load_dotenv
                load_dotenv(dotenv_path=str(env_file), override=True)
                
                # Import after changing directory to ensure .env is loaded
                from broca.token_auth.token import get_token_secret, generate_token
                from broca.token_auth.defaults import get_default_identity
                
                # Should be able to get secret from .env
                secret = get_token_secret()
                assert secret == test_secret
                
                # Generate token using secret from .env
                identity = get_default_identity()
                token, payload = generate_token(
                    sub=identity.get("sub", "test.user"),
                    name=identity.get("name", "Test User"),
                    scopes=["filesystem:write"],
                    expiry_seconds=300,
                    secret_key=secret
                )
                
                # Verify token can be verified with the same secret
                from broca.token_auth.token import verify_token
                verified_payload = verify_token(token, secret)
                assert verified_payload is not None
                assert verified_payload["sub"] == identity.get("sub", "test.user")
            finally:
                os.chdir(original_cwd)
                # Clean up environment
                monkeypatch.delenv("BROCA_TOKEN_SECRET", raising=False)
    
    def test_approval_system_verification_with_secret_in_env_file(self, monkeypatch):
        """Test that approval system can verify tokens when secret is only in .env file."""
        # Remove from environment if present
        monkeypatch.delenv("BROCA_TOKEN_SECRET", raising=False)
        
        # Create temporary directory with .env file
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"
            test_secret = "test_secret_from_env_file_67890"
            env_file.write_text(f"BROCA_TOKEN_SECRET={test_secret}\n")
            
            # Change to the temporary directory so .env is found
            original_cwd = os.getcwd()
            try:
                os.chdir(tmpdir)
                
                # Force reload of dotenv by calling load_dotenv with explicit path
                from dotenv import load_dotenv
                load_dotenv(dotenv_path=str(env_file), override=True)
                
                # Generate token first (using secret from .env)
                from broca.token_auth.token import get_token_secret, generate_token
                from broca.token_auth.defaults import get_default_identity
                
                secret = get_token_secret()
                assert secret == test_secret
                identity = get_default_identity()
                token, payload = generate_token(
                    sub=identity.get("sub", "test.user"),
                    name=identity.get("name", "Test User"),
                    scopes=["filesystem:write", "project:write", "memory:write"],
                    expiry_seconds=300,
                    secret_key=secret
                )
                
                # Now verify using approval system (should load from .env)
                approval_system = ApprovalSystem()
                result = approval_system.verify_approval(token)
                
                assert result.valid is True
                assert result.error is None
            finally:
                os.chdir(original_cwd)
                # Clean up environment
                monkeypatch.delenv("BROCA_TOKEN_SECRET", raising=False)
    
    def test_cli_token_works_with_approval_system_when_secret_in_env_file(self, monkeypatch):
        """Test that CLI-generated tokens work with approval system when secret is only in .env."""
        # Remove from environment if present
        monkeypatch.delenv("BROCA_TOKEN_SECRET", raising=False)
        
        # Create temporary directory with .env file
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"
            test_secret = "test_secret_from_env_file_cli"
            env_file.write_text(f"BROCA_TOKEN_SECRET={test_secret}\n")
            
            # Change to the temporary directory so .env is found
            original_cwd = os.getcwd()
            try:
                os.chdir(tmpdir)
                
                # Force reload of dotenv by calling load_dotenv with explicit path
                from dotenv import load_dotenv
                load_dotenv(dotenv_path=str(env_file), override=True)
                
                # Generate token (simulating CLI generation)
                from broca.token_auth.token import get_token_secret, generate_token
                from broca.token_auth.defaults import get_default_identity
                
                secret = get_token_secret()
                assert secret == test_secret
                identity = get_default_identity()
                cli_token, payload = generate_token(
                    sub=identity.get("sub", "test.user"),
                    name=identity.get("name", "Test User"),
                    scopes=["filesystem:write", "project:write", "memory:write"],
                    expiry_seconds=300,
                    secret_key=secret
                )
                
                # Use token with approval system (should load from .env)
                tool = EnvironmentAccessTool()
                
                # Escalate to AUTONOMOUS
                result = tool.execute(
                    action="request_escalation",
                    target_level="AUTONOMOUS",
                    rationale="Test"
                )
                request_id = result["request_id"]
                tool.execute(action="approve_escalation", request_id=request_id)
                
                # Use CLI-generated token in control_actuator
                test_file = Path(tmpdir) / "test.txt"
                result = tool.execute(
                    action="control_actuator",
                    actuator_id="filesystem_actuator",
                    operation="create_file",
                    parameters={
                        "path": str(test_file),
                        "content": "test content",
                        "approval_token": cli_token
                    }
                )
                
                assert result["success"] is True
                assert test_file.exists()
            finally:
                os.chdir(original_cwd)
                # Clean up environment
                monkeypatch.delenv("BROCA_TOKEN_SECRET", raising=False)

