#!/usr/bin/env python3
"""
rehydration.fixed.py

A safe, cleaned scaffold for boot-time rehydration derived from an imported
rehydration.py. This fixed version is read-first and runs in DRY-RUN mode by
default. To perform any state-changing writes, run with --apply and ensure you
have provided operator approvals and actuator token provenance per the
project's protocol.

Behavior (default): perform read-only checks and print a human-readable
summary. If run with --apply, the script may write the rehydration summary
artifact (atomic write) and perform other authorized state-changing actions.

This file was autogenerated by an assistant as a suggested fixed scaffold.
It does NOT perform signing or secret handling by itself.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from datetime import datetime, timezone
import tempfile
import shutil
import logging

LOG = logging.getLogger("rehydration.fixed")
logging.basicConfig(level=logging.INFO)

# Configurable paths (relative to repo root by default)
REPO_ROOT = Path.cwd()
SHUTDOWN_JSON = REPO_ROOT / ".shutdown_persistence.json"
ENV_FILE = REPO_ROOT / ".env"
ARTIFACTS_DIR = REPO_ROOT / "docs" / "external_artifacts" / "home_wizard_broca" / "artifacts"
REHYDRATION_ARTIFACT = ARTIFACTS_DIR / "REHYDRATION_SUMMARY.v0.2.md"
POINTER_FILE = REPO_ROOT / "docs" / "external_artifacts" / "home_wizard_broca" / "broca.session.pointer"


def _read_env_file(env_path: Path) -> dict:
    """Very small .env parser: returns dict of key->value. Does not export to os.environ.
    Handles simple KEY=VALUE pairs and quoted values."""
    out = {}
    if not env_path.exists():
        return out
    with env_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip()
            if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
                v = v[1:-1]
            out[k] = v
    return out


def load_secret_candidate() -> dict:
    """Return a small dict describing where a token secret may be found.
    This function does NOT return the secret value; it only reports provenance
    candidates for human review.
    """
    candidates = {}
    # env var
    env_val = os.environ.get("BROCA_TOKEN_SECRET")
    candidates["env_present"] = bool(env_val)
    # .env file
    envs = _read_env_file(ENV_FILE)
    candidates["env_file_has_broca_token_secret"] = "BROCA_TOKEN_SECRET" in envs
    # temporary token file (imported as external artifact)
    tmp_token = REPO_ROOT / ".temporary_token.txt"
    candidates["temporary_token_file_exists"] = tmp_token.exists()
    return candidates


def load_persistence_gate() -> dict:
    """Read .shutdown_persistence.json and return a summary dict.
    This performs only structural validation (presence of fields) in dry-run
    mode. Signature/HMAC verification requires an approved secret and is
    performed by higher-level procedures with operator approval.
    """
    if not SHUTDOWN_JSON.exists():
        return {"enabled": False, "reason": "no_shutdown_file"}
    try:
        with SHUTDOWN_JSON.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        return {"enabled": False, "reason": f"invalid_json: {e}"}
    payload = data.get("payload") if isinstance(data, dict) else None
    hmac_val = data.get("hmac") if isinstance(data, dict) else None
    summary = {
        "payload_present": bool(payload),
        "hmac_present": bool(hmac_val),
        "persistence_enabled": bool(payload and payload.get("persistence_enabled")),
        "created_by": payload.get("created_by") if payload else None,
        "jti": payload.get("jti") if payload else None,
        "exp": payload.get("exp") if payload else None,
    }
    return summary


def hydrate_pointers_and_artifacts() -> dict:
    """Read pointer and artifact summaries from the imported external artifacts
    area (read-only). Returns a small summary dict.
    """
    pointer = None
    if POINTER_FILE.exists():
        try:
            pointer = POINTER_FILE.read_text(encoding="utf-8").strip()
        except Exception:
            pointer = None
    # list artifacts in the imported artifacts folder
    artifacts = []
    art_root = REPO_ROOT / "docs" / "external_artifacts" / "home_wizard_broca" / "artifacts"
    if art_root.exists():
        for p in sorted(art_root.glob("**/*")):
            if p.is_file():
                artifacts.append(str(p.relative_to(REPO_ROOT)))
    return {"pointer": pointer, "artifacts": artifacts}


def hydrate_memory_graph() -> dict:
    """Attempt to inspect local memory artifacts (memories.db) and vector index.
    This is non-destructive: it only reports counts if the files exist. If
    embedding/index libraries are not installed, this will still return file
    existence and sizes.
    """
    mem_db = REPO_ROOT / "memories.db"
    vec_index = REPO_ROOT / "memories.faiss"
    res = {}
    res["mem_db_exists"] = mem_db.exists()
    res["mem_db_size"] = mem_db.stat().st_size if mem_db.exists() else None
    res["vec_index_exists"] = vec_index.exists()
    res["vec_index_size"] = vec_index.stat().st_size if vec_index.exists() else None
    # If sqlite3 is available, try to get a count
    try:
        import sqlite3
        if mem_db.exists():
            conn = sqlite3.connect(str(mem_db))
            cur = conn.cursor()
            cur.execute("SELECT COUNT(*) FROM memories")
            row = cur.fetchone()
            res["memories_count"] = row[0] if row else None
            conn.close()
    except Exception:
        res["memories_count"] = None
    return res


def verify_self_consistency() -> dict:
    """Run a non-mutative self-consistency check using the local ConsistencyChecker
    if available. This function will not mutate the self-model; it only calls
    the validator and returns its summary or an explanatory message if the
    validator is not available.
    """
    try:
        from broca.self_model.consistency import ConsistencyChecker
        from broca.self_model.model import SelfModel
        checker = ConsistencyChecker()
        try:
            sm = SelfModel.load() if hasattr(SelfModel, "load") else None
        except Exception:
            sm = None
        # validate a no-op example response as a lightweight smoke test
        example_resp = "This is a consistency check run; no mutation intended."
        if sm is None:
            return {"ok": True, "note": "SelfModel loader not available; skipped detailed check"}
        res = checker.validate(response=example_resp, self_model=sm, conversation_context=None)
        return {"ok": res.is_consistent, "violations": res.violations, "severity": res.severity}
    except Exception as e:
        return {"ok": True, "note": f"consistency-check-unavailable: {e}"}


def build_rehydration_summary(state: dict, apply: bool = False) -> str:
    """Compose a human-readable rehydration summary. If apply==True and the
    caller has approval, write the artifact atomically. Otherwise, return the
    text (dry-run).
    """
    lines = []
    lines.append("# REHYDRATION_SUMMARY.v0.2 - (fixed scaffold)")
    lines.append("")
    lines.append(f"Run time (UTC): {datetime.now(timezone.utc).isoformat()}")
    lines.append("")
    lines.append("PERSISTENCE GATE:")
    for k, v in state.get("persistence", {}).items():
        lines.append(f"- {k}: {v}")
    lines.append("")
    lines.append("POINTERS & ARTIFACTS:")
    pointer = state.get("pointer")
    lines.append(f"- pointer: {pointer}")
    for a in state.get("artifacts", []):
        lines.append(f"- artifact: {a}")
    lines.append("")
    lines.append("MEMORY & INDEX SUMMARY:")
    for k, v in state.get("memory", {}).items():
        lines.append(f"- {k}: {v}")
    lines.append("")
    lines.append("CONSISTENCY CHECK:")
    cons = state.get("consistency", {})
    lines.append(f"- ok: {cons.get('ok')}")
    if cons.get("violations"):
        lines.append(f"- violations: {cons.get('violations')}")
    lines.append("")
    lines.append("NEXT STEPS:")
    lines.append("- Provide Plan + Approval and actuator provenance to perform state-changing writes.")
    body = "\n".join(lines)

    if apply:
        # Atomic write to REHYDRATION_ARTIFACT
        REHYDRATION_ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
        tmp = Path(tempfile.mkstemp(prefix="rehydration_", suffix=".tmp")[1])
        try:
            tmp.write_text(body, encoding="utf-8")
            os.replace(str(tmp), str(REHYDRATION_ARTIFACT))
            LOG.info(f"Wrote rehydration summary to {REHYDRATION_ARTIFACT}")
        finally:
            if tmp.exists():
                try:
                    tmp.unlink()
                except Exception:
                    pass
    return body


def run_dry_run() -> dict:
    state = {}
    state["persistence"] = load_persistence_gate()
    ha = hydrate_pointers_and_artifacts()
    state["pointer"] = ha.get("pointer")
    state["artifacts"] = ha.get("artifacts")
    state["memory"] = hydrate_memory_graph()
    state["consistency"] = verify_self_consistency()
    return state


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Rehydration fixed scaffold (dry-run by default)")
    parser.add_argument("--apply", action="store_true", help="If set, perform authorized state-changing writes (requires operator approval)")
    args = parser.parse_args(argv)

    LOG.info("Starting rehydration.fixed (dry-run=%s)", not args.apply)
    candidates = load_secret_candidate()
    LOG.info("Secret provenance candidates: %s", candidates)

    state = run_dry_run()
    summary = build_rehydration_summary(state, apply=args.apply)
    print(summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
